name: reachnes_main_env
channels:
  - numba
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.14
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.6
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.5
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.4
  - aws-sdk-cpp=1.11.267
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cffi=1.16.0
  - colorama=0.4.6
  - cudatoolkit=11.8.0
  - expat=2.6.2
  - gcc_impl_linux-64=13.2.0
  - gcc_linux-64=13.2.0
  - gflags=2.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - graph-tool-base=2.59
  - gxx_impl_linux-64=13.2.0
  - gxx_linux-64=13.2.0
  - icc_rt=2020.2
  - icu=73.2
  - joblib=1.3.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libabseil=20240116.1
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.6
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.26
  - libparquet=15.0.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsanitizer=13.2.0
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - ncurses=6.4.20240210
  - numba=0.59.1
  - numpy=1.26.4
  - openssl=3.2.1
  - orc=2.0.0
  - pandas=2.2.1
  - pip=24.0
  - pyarrow=15.0.2
  - pycparser=2.22
  - python=3.10.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.1
  - rdma-core=51.0
  - re2=2023.09.01
  - readline=8.2
  - s2n=1.4.8
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - setuptools=69.2.0
  - six=1.16.0
  - snappy=1.1.10
  - sparsehash=2.0.4
  - sysroot_linux-64=2.12
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - tqdm=4.66.2
  - tzdata=2024a
  - ucx=1.15.0
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
