name: reachnes_main_env
channels:
  - numba
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aws-c-auth=0.7.17
  - aws-c-cal=0.6.11
  - aws-c-common=0.9.15
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.7
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.7
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.6
  - aws-sdk-cpp=1.11.267
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - colorama=0.4.6
  - expat=2.6.2
  - gcc_impl_linux-64=13.2.0
  - gcc_linux-64=13.2.0
  - gflags=2.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - graph-tool-base=2.59
  - gxx_impl_linux-64=13.2.0
  - gxx_linux-64=13.2.0
  - icc_rt=2020.2
  - icu=73.2
  - joblib=1.4.0
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libabseil=20240116.1
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libblas=3.9.0
  - libboost=1.84.0
  - libboost-python=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.1
  - libhwloc=2.10.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.6
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=15.0.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsanitizer=13.2.0
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - orc=2.0.0
  - pip=24.0
  - pycparser=2.22
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - rdma-core=51.0
  - re2=2023.09.01
  - readline=8.2
  - s2n=1.4.9
  - setuptools=69.5.1
  - six=1.16.0
  - snappy=1.2.0
  - sparsehash=2.0.4
  - sysroot_linux-64=2.12
  - tbb=2021.12.0
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - tqdm=4.66.2
  - tzdata=2024a
  - ucx=1.15.0
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - zstd=1.5.5
  - pip:
    - aiohttp==3.9.4
    - aiosignal==1.3.1
    - alabaster==0.7.16
    - annotated-types==0.6.0
    - async-timeout==4.0.3
    - attrs==23.2.0
    - autopep8==2.1.0
    - babel==2.14.0
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - dgl==1.1.3
    - dglgo==0.0.2
    - docutils==0.20.1
    - filelock==3.9.0
    - frozenlist==1.4.1
    - fsspec==2023.4.0
    - idna==3.7
    - imagesize==1.4.1
    - isort==5.13.2
    - jinja2==3.1.2
    - lightning==2.2.2
    - lightning-utilities==0.11.2
    - littleutils==0.2.2
    - llvmlite==0.42.0
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.5
    - networkx==3.2.1
    - numba==0.59.1
    - numpy==1.26.4
    - numpydoc==1.7.0
    - ogb==1.3.6
    - outdated==0.2.2
    - packaging==24.0
    - pandas==2.2.2
    - pillow==10.3.0
    - psutil==5.9.8
    - pyarrow==15.0.2
    - pycodestyle==2.11.1
    - pydantic==2.7.0
    - pydantic-core==2.18.1
    - pyg-lib==0.3.1+pt21cpu
    - pygments==2.17.2
    - pyparsing==3.1.2
    - pytorch-lightning==2.2.2
    - pyyaml==6.0.1
    - rdkit-pypi==2022.9.5
    - requests==2.31.0
    - rich==13.7.1
    - ruamel-yaml==0.18.6
    - ruamel-yaml-clib==0.2.8
    - scikit-learn==1.4.2
    - scipy==1.13.0
    - shellingham==1.5.4
    - snowballstemmer==2.2.0
    - sphinx==7.2.6
    - sphinxcontrib-applehelp==1.0.8
    - sphinxcontrib-devhelp==1.0.6
    - sphinxcontrib-htmlhelp==2.0.5
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.7
    - sphinxcontrib-serializinghtml==1.1.10
    - sympy==1.12
    - tabulate==0.9.0
    - tomli==2.0.1
    - torch==2.1.2+cpu
    - torch-cluster==1.6.3+pt21cpu
    - torch-geometric==2.5.2
    - torch-scatter==2.1.2+pt21cpu
    - torch-sparse==0.6.18+pt21cpu
    - torch-spline-conv==1.2.2+pt21cpu
    - torchmetrics==1.3.2
    - typer==0.12.3
    - typing-extensions==4.8.0
    - urllib3==2.2.1
    - yarl==1.9.4
    - zstandard==0.22.0
