name: neb_dggan_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.08.22
  - certifi=2021.5.30
  - cudatoolkit=10.0.130
  - cudnn=7.3.1
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=21.2.2
  - python=3.6.13
  - readline=8.2
  - setuptools=58.0.4
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - astor==0.8.1
    - cached-property==1.5.2
    - dataclasses==0.8
    - decorator==5.1.1
    - gast==0.2.2
    - gitdb==4.0.9
    - gitpython==3.1.18
    - google-pasta==0.2.0
    - grpcio==1.48.2
    - h5py==3.1.0
    - importlib-metadata==4.8.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.3.7
    - networkx==2.2
    - numpy==1.19.5
    - opt-einsum==3.3.0
    - pandas==0.24.2
    - protobuf==3.19.6
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - pyyaml==5.4.1
    - scikit-learn==0.20.4
    - scipy==1.5.4
    - six==1.16.0
    - smmap==5.0.0
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - typing-extensions==4.1.1
    - werkzeug==2.0.3
    - wrapt==1.16.0
    - zipp==3.6.0
