methods:
  app:
    disable: False
    modes:
      directed: True
      weighted: False
      node_attributed: False
      edge_attributed: False
      dynamic: False
    hyperparameters:
      dimensions:
        default: 128
        type: int
        description: Dimension of the concatenated proximal embeddings.
      jump_factor:
        default: 0.50
        type: float
        description: Jumping factor of the APP method.
      steps:
        default: 3
        type: int
        description: Maximum number of random walk steps.