name: neb_app_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - dbus=1.13.6
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - graphite2=1.3.13
  - harfbuzz=5.3.0
  - icu=70.1
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.19.3
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - make=4.3
  - ncurses=6.3
  - networkx=2.8.8
  - numpy=1.23.5
  - openjdk=11.0.13
  - openssl=3.0.7
  - pandas=1.5.2
  - pcre2=10.40
  - pip=22.3.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.6
  - pyyaml=6.0
  - readline=8.1.2
  - scipy=1.9.3
  - setuptools=65.5.1
  - six=1.16.0
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - gitdb==4.0.10
      - gitpython==3.1.31
      - outdated==0.2.2
      - smmap==5.0.0